### ISSUE TITLE
ci: `Build` action has been consistently failing `macos-arm64-build`

### ISSUE THREAD

**Issue by ginglis13** [runfinch/finch-core#137]
The Build action has been consistently failing for the last month: https://github.com/runfinch/finch-core/actions/workflows/release.yaml

The log lines in step `Make and release deps` before timeout have been:

```
if [ "Darwin" != "Linux" -a ! -e "/opt/homebrew/bin/nerdctl" ]; then ln -sf nerdctl.lima "/opt/homebrew/bin/nerdctl"; fi
if [ "Darwin" != "Linux" -a ! -e "/opt/homebrew/bin/apptainer" ]; then ln -sf apptainer.lima "/opt/homebrew/bin/apptainer"; fi
sudo may prompt for password to run FileMonitor
Error: The operation was canceled. # <-- timeout, cancelled workflow
```

This message is coming from https://github.com/runfinch/finch-core/blob/08a4ca2a9285f1dd2fac3bd4701087b1b2fdec87/bin/lima-and-qemu.pl#L46

Still looking to verify but the smoking gun is that the script is hanging on a prompt for password.

e: On my machine macOS Ventura 13.4 M1 chip:

```
./bin/lima-and-qemu.pl                                            
ls: /opt/homebrew/bin/limactl: No such file or directory
Missing argument in sprintf at ./bin/lima-and-qemu.pl line 213.
sudo may prompt for password to run FileMonitor
Password:
```

**Comment by vsiravar** [comment]
GitHub runners use [passwordless sudo](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#administrative-privileges). However runners provisioned via [finch infra](https://github.com/runfinch/infrastructure) don't allow passwordless sudo.

**Comment by ginglis13** [comment]
@vsiravar thanks, moving this over to https://github.com/runfinch/infrastructure/issues/367 for tracking since this appears to be an issue w/ the ASG/instances
